### PR TITLE
Automated doc generator

### PR DESCRIPTION
**Pull request by rudygodoy**
Adds automated doc generator using `@digix/doxity`. This PR for #64 has all the necessary files to generate the docs.

Docs should be generated under the `/docs` directory. Install dev dependencies running either `npm install` or `yarn`, then do `npm run docs:compile && npm run docs:publish`.

To use the generated files on GitHub Pages we must commit the `/docs` directory to the master branch.

Notes:
- I've tested locally and it works. I'm not sure about adding generated files to the repo in the PR.
- Somehow the `docs:build` target, which is a wrapper for the stated commands, doesn't work, so you have to run the individual commands.
- The `docs:develop` target which wraps `doxity develop`  may also have issues. To visualize and navigate through generated documents, try running `gatsby develop` from the `scripts/doxity/` folder.
- If the `docs:publish` doesn't generate html files under `/docs`, try editing `scripts/doxity/config.toml` and leave the `linkPrefix` setting empty, then run it again.
- We may want to remove the `docs:init` target since the doxity project it's already initialized.

### CODE REVIEW

**Comment by izqui** [comment]
Awesome contribution, thanks for taking the time! 

Can you make the `dev` branch the target of the PR? It is the branch we are actively developing to now.

**Comment by bingen** [comment]
See this: https://github.com/aragon/hack-docs/pull/2
@izqui maybe we should close this one?

**Comment by rudygodoy** [comment]
@bingen @izqui I believe it's safe to close this.

**Comment by izqui** [comment]
Thanks for the contribution @rudygodoy, sorry that it got done in another way

**Pull request closed without merging**
