### PR TITLE
Closes #481, disabled linter warnings about empty blocks

### LINKED ISSUE #481: Lint errors in master branch on ACLSyntaxSugar and AppProxyUpgradeable
$ npm run lint

> @aragon/os@4.0.1 lint /home/greg/Development/src/aragonOS/usetech
> solium --dir ./contracts

contracts/acl/ACLSyntaxSugar.sol
  9:53    error    Code contains empty block    no-empty-blocks

contracts/apps/AppProxyUpgradeable.sol
  16:4    error    Code contains empty block    no-empty-blocks

✖ 2 errors found.

### PR DESCRIPTION
**Pull request by gregzaitsev**

### CODE REVIEW

**Comment by sohkai** [comment]
Thanks for the fast response, @gregzaitsev! Before merging, we just need you to sign the contributor agreement :).

**Review by sohkai — APPROVED** [review]
👍 Could you also bump the `solium` dependency to latest?

**Comment by gregzaitsev** [comment]
Thanks, @sohkai! I bumped linter to latest as you said and signed agreement from both myself and my company - usetech-llc (it is still pending for some reason though).

**Comment by sohkai** [comment]
@gregzaitsev I think it's cause you committed with a different user and Github / the CLA bot is a bit confused. One way to trick this is to change your git config to use your Github user's email and name, rebase the commits, and then force push.

**Comment by gregzaitsev** [comment]
Thanks! Amending author's email and name worked!

**Comment by sohkai** [comment]
Hey @gregzaitsev, did you mean to close this PR?

**Comment by sohkai** [comment]
Ohh actually I just realized I did these changes in https://github.com/aragon/aragonOS/pull/476 a few days ago as well 😅. No wonder I was getting a bit of deja vu.

**Pull request closed without merging**
