### PR TITLE
chore: upgrade solidity-coverage to v0.6+

### PR DESCRIPTION
**Pull request by sohkai**
Upgrades `solidity-coverage`.

A number of tests invoking the fallback function are now failing with an out of gas on the new version, likely due to new instrumentation rules. Previously they were operating within the limit, even under instrumentation.

cc @cgewecke

### CODE REVIEW

**Comment by cgewecke** [comment]
@sohkai Taking a look today... `send` and `transfer` continue to fail on our tests as well even though the updated coverage client (6.4.5) uses a new vm option which should make  instrumentation free. For example [these tests]((https://github.com/OpenZeppelin/openzeppelin-solidity/blob/489d2e85f10c68ff977bdd983360b361c4422423/test/introspection/SupportsInterface.behavior.js#L48-L54)) at zeppelin run a gas check for ERC165 interfaces and seem okI.

**Comment by cgewecke** [comment]
@sohkai Could you retry with `0.6.2` when you have a chance? Our tests for this case are finally passing and hopefully you should be able to unskip all send / transfer tests.

**Comment by sohkai** [comment]
@cgewecke Can confirm with the new version that all the ETH transfers are working under coverage 🎉.

Thanks so much for helping out on this!

**Comment by facuspagnuolo** [comment]
Let's create an issue to tackle the uncovered lines

**Comment by sohkai** [comment]
@facuspagnuolo Not sure why coverage decreased (if anything, not skipping those tests should increase it...), but we do have #514 for the few areas of coverage we previously missed :).

**Pull request merged**
