### PR TITLE
Experiment: remove parameters from ACL

### PR DESCRIPTION
**Pull request by bingen**
```
                              CODE DEPOSIT COST    DEPLOYED BYTES     INITIALIZATION BYTES
ACL.json                      772000 less gas      -3860              0
APMRegistry.json              49400 less gas       -247               0
AppStub.json                  110200 less gas      -551               0
AppStub2.json                 40400 less gas       -202               0
AragonApp.json                40400 less gas       -202               0
ENSSubdomainRegistrar.json    57000 less gas       -285               0
EVMScriptRegistry.json        61600 less gas       -308               0
EVMScriptRegistryFactory.json Same                 0                  -308
Kernel.json                   122000 less gas      -610               0
KernelOverloadMock.json       2800 less gas        -14                0
Repo.json                     44200 less gas       -221               0
UnsafeAppStub.json            110200 less gas      -551               0
UnsafeAragonApp.json          40400 less gas       -202               0
UnsafeRepo.json               17400 less gas       -87                0
```

### CODE REVIEW

**Comment by bingen** [comment]
Closing it, it's just to see the numbers.

**Comment by sohkai** [comment]
@bingen We could add a `SimpleACL` that removes all the params (but keep the `authP` modifiers, which would pass information that are not used).

**Comment by bingen** [comment]
Yes, absolutely. That's why I immediately closed it, it's not intended to be the real solution. Just wanted to a have a quick look at the numbers. Let's finish the discussion and make a final decision and I can go for it if you want.

**Comment by bingen** [comment]
Btw, partially inspired by this: https://youtu.be/zwm1ZQQMVF0?t=1201
;-)

**Pull request closed without merging**
