### PR TITLE
Fix incorrect appId constants

### LINKED ISSUE #282: Fix incorrect appId constants
There are a bunch of constants that have bad appIds (there are maybe more):

```solidity
    // IEVMScriptRegistry.sol
    bytes32 constant public EVMSCRIPT_REGISTRY_APP_ID = keccak256("evmreg.aragonpm.eth");
 
    // KernelStorage.sol
    bytes32 constant public KERNEL_APP_ID = keccak256("kernel.aragonpm.eth");
    bytes32 constant public ACL_APP_ID = keccak256("acl.aragonpm.eth");
```

should be `apmNamehash("evmreg")` where `apmNamehash` is something like: 

```solidity
bytes32 constant public ETH_NODE = keccak256(keccak256(0), keccak256("eth"));
bytes32 constant public APM_NODE = keccak256(keccak256(ETH_NODE), keccak256("aragonpm"));

function apmNamehash(string name) internal pure returns (bytes32) {
  return keccak256(APM_NODE, keccak256(name));
}
```

### PR DESCRIPTION
**Pull request by bingen**
Closes #282.

### CODE REVIEW

**Comment by izqui** [comment]
Also i think the logic for calculating the namehash is wrong, can you add tests against `eth-ens-namehash`?

**Comment by bingen** [comment]
I tried importing `KernelConstants` from `IEVMScriptRegistry` and I was having gas issues. I'll try this way. What about `APP_ADDR_NAMESPACE`? Do you want me to move it to the new `APMNameHash` file or to have it repeated?

**Comment by izqui** [comment]
`APP_ADDR_NAMESPACE` should be in `KernelConstants`, if that is giving you issues the just repeat it.

**Comment by izqui** [comment]
lgtm

**Comment by izqui** [comment]
i'd say this is ready to merge from my pov, no need for further review!

**Pull request merged**
