### PR TITLE
Fix kernel_apps and zeppelin_StandardToken unit tests

### PR DESCRIPTION
**Pull request by mnaamani**
Fix broken test cases.

### CODE REVIEW

**Comment by sohkai** [comment]
Hey @mnaamani, thanks for the pull requests!

I'm not sure these tests are actually broken though—usually `.toNumber()` will be implicitly called for number conversions and the token in that test doesn't need to be initialized with a starting balance (although, I admit, there's a lot of duplication in that test when the `beforeEach()` already handles token creation).

Our CI suites also don't have them failing.

**Comment by mnaamani** [comment]
Hi @sohkai its a real pleasure to contribute to this great project.
Yes it seems my setup is different than what the CI is running with, specifically the version of truffle and solc which explains why I'm only seeing the errors.

Test output (only 2,3,4 are relevant)
```
  239 passing (4m)
  4 failing

  1) Contract: Constants
       checks kernel constants:
     TypeError: keccakConstants.ETH_NODE is not a function
      at Context.it (test/keccak_constants.js:17:74)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  2) Contract: Kernel apps
       upgradeable proxies
         initializing on proxy constructor
           was initialized on constructor:
     AssertionError: app should have been initialized: expected 69 to be a number or a date
      at Context.it (test/kernel_apps.js:104:24)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  3) Contract: Kernel apps
       upgradeable proxies
         not initializing on proxy constructor
           setting app code in kernel
             can initialize:
     AssertionError: app should have been initialized: expected 110 to be a number or a date
      at Context.it (test/kernel_apps.js:154:28)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  4) Contract: StandardToken
       should return the correct allowance amount after approval:
     Error: StandardTokenMock contract constructor expected 2 arguments, received 0
      at /Users/mokhtar/npm/lib/node_modules/truffle/build/webpack:/packages/truffle-contract/contract.js:390:1
      at new Promise (<anonymous>)
      at /Users/mokhtar/npm/lib/node_modules/truffle/build/webpack:/packages/truffle-contract/contract.js:374:1
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

I'm on truffle `v4.1.13`  (repo's package.json is on `v4.0.5`). Perhaps there is a difference in the assertion library dependencies also which explains why I had to explicitly invoke `.toNumber()`. 

You are correct on the point about the token initialization in that test. Also it seems my version of truffle is doing better checking for expected arguments.

Thanks for looking at the PR, maybe it not a high priority now, and can be deferred.

**Comment by sohkai** [comment]
@mnaamani We definitely require `truffle@4.0.5` for `solc@4.18.0`.

The two initializing tests there also seem to fail oddly; it must be converting the results into a string instead?

**Comment by mnaamani** [comment]
Yes I believe so
>The two initializing tests there also seem to fail oddly; it must be converting the results into a string instead?

Oh you are seeing the same tests fail now with `truffle@4.0.5` as well ?

**Comment by sohkai** [comment]
@mnaamani Haven't yet. Could be how truffle uses the big numbers; I've seen / heard there's some changes happening with going towards `BN.js` instead of `bignumber.js` but not sure if that's happened in the version you were on.

**Comment by sohkai** [comment]
@mnaamani Are you still seeing this issue?

**Comment by mnaamani** [comment]
@sohkai I switched to latest dev branch with the same setup I had before. 

I'm no longer seeing the issues I identified.

It seems the correct version of truffle is now being used from `./node_modules/.bin/truffle` (instead of my globally installed version which was causing the issue)

**Comment by sohkai** [comment]
Merging or rebasing from `dev` should fix the `ETH_NODE` test failing :)

**Comment by mnaamani** [comment]
@sohkai Sorry my bad forgot to pull latest. All test passing.

**Comment by mnaamani** [comment]
Thanks for following up :+1:
We can close this PR now.

**Comment by sohkai** [comment]
@mnaamani Actually let's leave this open–we're going to be pushing to `pragma 0.4.24` soon and upgrade truffle versions so we'll merge the fix from here :).

**Comment by sohkai** [comment]
Closed by #383; we pulled the changes into there instead :).

**Pull request closed without merging**
