### PR TITLE
FIX: #223 - Rename ACL functions to reduce verbosity

### PR DESCRIPTION
**Pull request by pmespresso**
- Problem:

 when the ACL was inside the kernel to use more descriptive names, but now that it is its own component, it isn't needed.

- Changes:

1. createPermission(...) -> create(...)
2. _createPermission(...) -> _create(...)
3. grantPermission(...) -> grant(...)
4. revokePermission(...) -> revoke(...)
5. _setPermission(...) -> _set(...)

### CODE REVIEW

**Review by izqui — COMMENTED** [review]
This looks amazing, thanks so much for taking the time.

What do you think about also changing:
- `acl.setPermissionManager(...)` -> `acl.setManager(...)`? (Also getPermissionManager)
- `acl.grantPermissionP(...)` -> `acl.grantP(...)` or `acl.grantWithParams` (@sohkai which one do you prefer, i think i like `grantP` more)

**Comment by renexdev** [comment]
Great, its clear that in the context of ACL, the permission/access word is redundant... =)
acl.grantP +1

**Comment by sohkai** [comment]
Agree with `grantP`; we're using the short form everywhere so it's best to go along with it (even though I would advocate that `[name]` and `[name]P` are really easy to mistype/read 😉).

**Comment by sohkai** [comment]
> Should we merge it to an aragonOS 4 branch when we do?

Let's do it!

**Comment by onbjerg** [comment]
I strongly dislike `authP` and `grantP`. It's not clear what they do at first glance from a new developers standpoint, and since we're removing redundancy in this PR, I also think we could add additional context where it makes sense.

Code should be as readable as possible without comments 😊

**Comment by yjkimjunior** [comment]
On second thought, I agree with @onbjerg that grantPermissionP ought to be changed to grantWithParams rather than grantP, to make it clear even at first glance that there is a difference.

**Comment by sohkai** [comment]
Also strongly agree, but then we will literally be breaking everything in our world in 4.0. Migration docs 🤞

**Comment by onbjerg** [comment]
@sohkai We need to do those anyway, this is literally breaking everything in our world, with or without the `grantP` change

**Comment by sohkai** [comment]
Given the time since this was made, and that this would mean another breaking change (to an API that is used in quite a lot of places now), we won't be modifying these interfaces.

Thanks for doing this though @yjkimjunior, and sorry this didn't make it to `aragonOS@4`!

**Pull request closed without merging**
